name: Deploy Frontend
on:
  push:
    branches:
      - master # check your repo, your default branch might be main!
  pull_request:
    branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t guillesanz21/course.dockerk8.tests -f Dockerfile.dev .
      - run: docker run -e CI=true guillesanz21/course.dockerk8.tests npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: test-CI-AWS
          environment_name: Testciaws-env
          existing_bucket_name: elasticbeanstalk-eu-west-2-423236424530
          region: eu-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'